# Generated by Django 4.1.7 on 2023-03-31 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='delivery_info',
        ),
        migrations.AddField(
            model_name='transaction',
            name='delivery_email',
            field=models.CharField(default='A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='delivery_name',
            field=models.CharField(default='A', max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DeliveryInfo',
        ),
    ]
