# Generated by Django 4.1.7 on 2023-04-01 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_transaction_delivery_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='callback_url',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.carddetails'),
        ),
    ]
