# Generated by Django 4.1.7 on 2023-04-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_transaction_id_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='expiry_date',
            field=models.CharField(max_length=5),
        ),
    ]
