# Generated by Django 4.1.7 on 2023-04-02 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_carddetails_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_4_card_digits', models.SmallIntegerField()),
                ('type', models.CharField(choices=[('payment', 'Paid'), ('refund', 'Refund')], default='payment', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.carddetails')),
            ],
        ),
    ]
