# Generated by Django 4.1.7 on 2023-04-02 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.transaction'),
        ),
    ]
